/*ç
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import dao.BancoDeDados;
import entities.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author win
 */
public class PaginaCadastro extends javax.swing.JFrame {

    private String nivelConhecimento = "Baixo";

    /**
     * Creates new form CadastrePage
     */
    public PaginaCadastro() {
        try {
            initComponents();
            componentesAlterados();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: " + ex.getMessage());
        }
    }

    public void componentesAlterados() throws ParseException {
        panelName.setBackground(Color.WHITE);
        panelPassword.setBackground(Color.white);
        adicionarPlaceHolderEstilo(txtName);
        adicionarPlaceHolderEstilo(txtPassword);
        adicionarPlaceHolderEstilo(txtEmail);
        txtPassword.setEchoChar((char) 0);
        panelEmail.setBackground(Color.WHITE);
        lblNomeInvalido.setForeground(Color.red);
        lblEmailIncorreto.setForeground(Color.red);
        lblSenhaIncorreta.setForeground(Color.red);
        lblUsuarioJáCadastrado.setForeground(Color.red);
        lblNomeInvalido.setVisible(false);
        lblEmailIncorreto.setVisible(false);
        lblSenhaIncorreta.setVisible(false);
        lblUsuarioJáCadastrado.setVisible(false);
        lblUsuarioCadastradoComSucesso.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/iconImage.png")));
    }

    public void entradasSaoVazias(String nome, String email, String senha) {
        if (nome.equals("Nome")) {
            adicionarEstiloBordaDeErro(panelName);
            lblNomeInvalido.setVisible(true);
        }
        if (email.equals("Email")) {
            adicionarEstiloBordaDeErro(panelEmail);
            lblEmailIncorreto.setVisible(true);
        }
        if (senha.equals("Senha")) {
            adicionarEstiloBordaDeErro(panelPassword);
            lblSenhaIncorreta.setVisible(true);
        }
    }

    public void adicioanarErroUsuarioJaCadastrado() {
        lblUsuarioJáCadastrado.setVisible(true);
        adicionarEstiloBordaDeErro(panelEmail);
        adicionarEstiloBordaDeErro(panelName);
        adicionarEstiloBordaDeErro(panelPassword);
    }

    public void adicionarEstiloBordaDeErro(JPanel panel) {
        LineBorder border = new LineBorder(Color.red, 2);
        panel.setBorder(border);
    }

    public void removerEstiloBordaDeErro(JPanel panel) {
        LineBorder border = new LineBorder(Color.black, 2);
        panel.setBorder(border);
    }

    public void adicionarFocusGainedEstiloBorda(JPanel panel) {
        LineBorder border = new LineBorder(Color.blue, 2);
        panel.setBorder(border);
    }

    public void adicionarFocusLostEstiloBorda(JPanel panel) {
        LineBorder border = new LineBorder(Color.black, 2);
        panel.setBorder(border);
    }

    public void adicionarPlaceHolderEstilo(JTextField text) {
        Font font = text.getFont();
        font = font.deriveFont(Font.ITALIC);
        text.setFont(font);
    }

    public void removerPlaceHolderEstilo(JTextField text) {
        Font font = text.getFont();
        font = font.deriveFont(Font.PLAIN);
        text.setFont(font);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelName = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        panelPassword = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        btnEye = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        panelEmail = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBaixoConhecimento = new javax.swing.JButton();
        btnAltoConhecimento = new javax.swing.JButton();
        btnMedioConhecimento = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblNomeInvalido = new javax.swing.JLabel();
        lblEmailIncorreto = new javax.swing.JLabel();
        lblSenhaIncorreta = new javax.swing.JLabel();
        lblUsuarioJáCadastrado = new javax.swing.JLabel();
        lblUsuarioCadastradoComSucesso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        panelName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtName.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        txtName.setText("Nome");
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nameImg.png"))); // NOI18N

        javax.swing.GroupLayout panelNameLayout = new javax.swing.GroupLayout(panelName);
        panelName.setLayout(panelNameLayout);
        panelNameLayout.setHorizontalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelNameLayout.setVerticalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName)
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panelName);
        panelName.setBounds(118, 97, 387, 60);

        panelPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPassword.setText("Senha");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        btnEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btnEyeNotVisible.png"))); // NOI18N
        btnEye.setBorder(null);
        btnEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEyeActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/passwordImg.png"))); // NOI18N

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEye, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPasswordLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword)
                            .addGroup(panelPasswordLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEye))))
                    .addGroup(panelPasswordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panelPassword);
        panelPassword.setBounds(120, 280, 387, 60);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Cadastre-se");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(159, 6, 277, 56);

        lblCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCadastro.setText("Já possui cadastro? Faça login");
        lblCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadastroMouseExited(evt);
            }
        });
        jPanel1.add(lblCadastro);
        lblCadastro.setBounds(210, 600, 196, 17);

        panelEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtEmail.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/emailImg.png"))); // NOI18N

        javax.swing.GroupLayout panelEmailLayout = new javax.swing.GroupLayout(panelEmail);
        panelEmail.setLayout(panelEmailLayout);
        panelEmailLayout.setHorizontalGroup(
            panelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEmailLayout.setVerticalGroup(
            panelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail)
                    .addGroup(panelEmailLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panelEmail);
        panelEmail.setBounds(118, 191, 390, 60);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Qual o seu nível de conhecimento sobre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(122, 376, 254, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Educação Financeira?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(122, 399, 210, 22);

        btnBaixoConhecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/checkBoxOk.png"))); // NOI18N
        btnBaixoConhecimento.setBorder(null);
        btnBaixoConhecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBaixoConhecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaixoConhecimentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBaixoConhecimento);
        btnBaixoConhecimento.setBounds(118, 433, 30, 30);

        btnAltoConhecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/checkBox.png"))); // NOI18N
        btnAltoConhecimento.setBorder(null);
        btnAltoConhecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltoConhecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltoConhecimentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAltoConhecimento);
        btnAltoConhecimento.setBounds(440, 440, 30, 20);

        btnMedioConhecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/checkBox.png"))); // NOI18N
        btnMedioConhecimento.setBorder(null);
        btnMedioConhecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedioConhecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedioConhecimentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedioConhecimento);
        btnMedioConhecimento.setBounds(270, 440, 30, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Alto");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 440, 50, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Baixo");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 440, 40, 17);

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btnCadastrar.png"))); // NOI18N
        btnCadastrar.setBorder(null);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar);
        btnCadastrar.setBounds(220, 480, 173, 60);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Médio");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 440, 40, 20);

        lblNomeInvalido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNomeInvalido.setText("Informe um nome!");
        jPanel1.add(lblNomeInvalido);
        lblNomeInvalido.setBounds(118, 157, 130, 17);

        lblEmailIncorreto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmailIncorreto.setText("Informe um email!");
        jPanel1.add(lblEmailIncorreto);
        lblEmailIncorreto.setBounds(120, 250, 160, 17);

        lblSenhaIncorreta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSenhaIncorreta.setText("Informe uma senha!");
        jPanel1.add(lblSenhaIncorreta);
        lblSenhaIncorreta.setBounds(120, 340, 140, 17);

        lblUsuarioJáCadastrado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuarioJáCadastrado.setText("Usuário já cadastrado!");
        jPanel1.add(lblUsuarioJáCadastrado);
        lblUsuarioJáCadastrado.setBounds(120, 250, 164, 16);

        lblUsuarioCadastradoComSucesso.setBackground(new java.awt.Color(51, 255, 0));
        lblUsuarioCadastradoComSucesso.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblUsuarioCadastradoComSucesso.setForeground(new java.awt.Color(51, 153, 0));
        lblUsuarioCadastradoComSucesso.setText("Usuáro cadastrado!");
        jPanel1.add(lblUsuarioCadastradoComSucesso);
        lblUsuarioCadastradoComSucesso.setBounds(120, 340, 150, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(623, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseEntered
        lblCadastro.setForeground(Color.blue);
    }//GEN-LAST:event_lblCadastroMouseEntered

    private void lblCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseExited
        lblCadastro.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCadastroMouseExited

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        lblNomeInvalido.setVisible(false);
        adicionarFocusGainedEstiloBorda(panelName);
        if (txtName.getText().equals("Nome")) {
            txtName.requestFocus();
            txtName.setText(null);
            removerPlaceHolderEstilo(txtName);
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        adicionarFocusLostEstiloBorda(panelName);
        if (txtName.getText().equals("")) {
            txtName.setText("Nome");
            adicionarPlaceHolderEstilo(txtName);
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        lblSenhaIncorreta.setVisible(false);
        adicionarFocusGainedEstiloBorda(panelPassword);
        if (txtPassword.getText().equals("Senha")) {
            txtPassword.requestFocus();
            txtPassword.setText(null);
            txtPassword.setEchoChar('*');
            removerPlaceHolderEstilo(txtPassword);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost

        adicionarFocusLostEstiloBorda(panelPassword);
        if (txtPassword.getText().equals("")) {
            txtPassword.setText("Senha");
            txtPassword.setEchoChar((char) 0);
            adicionarPlaceHolderEstilo(txtPassword);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnEyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEyeActionPerformed
        if (btnEye.isSelected()) {
            btnEye.setIcon(new ImageIcon(getClass().getResource("/assets/btnEyeIsVisible.png")));
            txtPassword.setEchoChar((char) 0);

        } else {
            btnEye.setIcon(new ImageIcon(getClass().getResource("/assets/btnEyeNotVisible.png")));
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_btnEyeActionPerformed

    private void lblCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseClicked
        new PaginaLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCadastroMouseClicked

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        lblEmailIncorreto.setVisible(false);
        lblUsuarioJáCadastrado.setVisible(false);
        adicionarFocusGainedEstiloBorda(panelEmail);
        if (txtEmail.getText().equals("Email")) {
            txtEmail.setText(null);
            txtEmail.requestFocus();
            removerPlaceHolderEstilo(txtEmail);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        adicionarFocusLostEstiloBorda(panelEmail);
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Email");
            adicionarPlaceHolderEstilo(txtEmail);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyPressed

    private void btnBaixoConhecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixoConhecimentoActionPerformed
        btnMedioConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBox.png")));
        btnBaixoConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBoxOk.png")));
        btnAltoConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBox.png")));
        nivelConhecimento = "Baixo";
    }//GEN-LAST:event_btnBaixoConhecimentoActionPerformed

    private void btnAltoConhecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltoConhecimentoActionPerformed
        btnMedioConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBox.png")));
        btnBaixoConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBox.png")));
        btnAltoConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBoxOk.png")));
        nivelConhecimento = "Alto";
    }//GEN-LAST:event_btnAltoConhecimentoActionPerformed

    private void btnMedioConhecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedioConhecimentoActionPerformed
        btnMedioConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBoxOk.png")));
        btnBaixoConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBox.png")));
        btnAltoConhecimento.setIcon(new ImageIcon(getClass().getResource("/assets/checkBox.png")));
        nivelConhecimento = "Medio";
    }//GEN-LAST:event_btnMedioConhecimentoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        lblUsuarioJáCadastrado.setVisible(false);
        lblUsuarioCadastradoComSucesso.setVisible(false);
        removerEstiloBordaDeErro(panelEmail);
        removerEstiloBordaDeErro(panelName);
        removerEstiloBordaDeErro(panelPassword);

        String nome, email, senha;
        nome = txtName.getText();
        email = txtEmail.getText();
        senha = txtPassword.getText();
        if (nome.equals("Nome") || email.equals("Email") || senha.equals("Senha")) {
            entradasSaoVazias(nome, email, senha);
        } else {
            Usuario usuario = new Usuario(email, senha, nome, nivelConhecimento);
            BancoDeDados bd;
            try {
                bd = new BancoDeDados();
                bd.cadastrar(usuario);
                lblUsuarioCadastradoComSucesso.setVisible(true);
                txtName.setText("Nome");
                txtEmail.setText("Email");
                txtPassword.setText("Senha");
                txtPassword.setEchoChar((char)0);
                dispose();
                new PaginaLogin().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                if(ex.getMessage().contains("Duplicate")){
                    lblUsuarioJáCadastrado.setVisible(true);
                    adicionarEstiloBordaDeErro(panelEmail);
                    adicionarEstiloBordaDeErro(panelName);
                    adicionarEstiloBordaDeErro(panelPassword);
                }else{
                    JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage());
                }
            }
        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(new FlatMacLightLaf());
                    break;

                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaAdministrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltoConhecimento;
    private javax.swing.JButton btnBaixoConhecimento;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JToggleButton btnEye;
    private javax.swing.JButton btnMedioConhecimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblEmailIncorreto;
    private javax.swing.JLabel lblNomeInvalido;
    private javax.swing.JLabel lblSenhaIncorreta;
    private javax.swing.JLabel lblUsuarioCadastradoComSucesso;
    private javax.swing.JLabel lblUsuarioJáCadastrado;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelName;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
