/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import dao.BancoDeDados;
import entities.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.UIManager;

/**
 *
 * @author kaik.salves
 */
public class PaginaLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public PaginaLogin() {
        initComponents();
        componentesAlterados();
    }

    public void componentesAlterados() {
        panelLogin.setBackground(Color.white);
        panelEmail.setBackground(Color.white);
        panelPassword.setBackground(Color.white);
        txtEmail.setBackground(new Color(0, 0, 0, 0));
        txtPassword.setBackground(new Color(0, 0, 0, 0));
        adicionarPlaceHolderEstilo(txtEmail);
        adicionarPlaceHolderEstilo(txtPassword);
        txtPassword.setEchoChar((char) 0);
        lblSenhaIncorreta.setVisible(false);
        lblSenhaIncorreta.setForeground(Color.red);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/iconImage.png")));

    }
    
    public void adicionarFocusGainedEstiloBorda(JPanel panel) {
        LineBorder border = new LineBorder(Color.blue, 2);
        panel.setBorder(border);
    }

    public void adicionarFocusLostEstiloBorda(JPanel panel) {
        LineBorder border = new LineBorder(Color.black, 2);
        panel.setBorder(border);
    }

    public void adicionarEstiloBordaDeErro() {
        lblSenhaIncorreta.setVisible(true);
        LineBorder border = new LineBorder(Color.RED, 2);
        panelEmail.setBorder(border);
        panelPassword.setBorder(border);
    }

    public void removerEstiloBordaDeErro() {
        LineBorder border = new LineBorder(Color.BLACK, 2);
        panelEmail.setBorder(border);
        panelPassword.setBorder(border);
    }

    public void removerPlaceHolderEstilo(JTextField text) {
        Font font = text.getFont();
        font = font.deriveFont(Font.PLAIN);
        text.setFont(font);
    }

    public void adicionarPlaceHolderEstilo(JTextField text) {
        Font font = text.getFont();
        font = font.deriveFont(Font.ITALIC);
        text.setFont(font);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        panelEmail = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelPassword = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        btnEye = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSenhaIncorreta = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        lblCadastrar = new javax.swing.JLabel();
        lblEntrarComoAdm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/emailImg.png"))); // NOI18N

        javax.swing.GroupLayout panelEmailLayout = new javax.swing.GroupLayout(panelEmail);
        panelEmail.setLayout(panelEmailLayout);
        panelEmailLayout.setHorizontalGroup(
            panelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEmailLayout.setVerticalGroup(
            panelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEmail)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPassword.setText("Senha");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        btnEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btnEyeNotVisible.png"))); // NOI18N
        btnEye.setBorder(null);
        btnEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEyeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/passwordImg.png"))); // NOI18N

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEye, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPasswordLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(panelPasswordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setText("LOGIN");

        lblSenhaIncorreta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSenhaIncorreta.setText("Senha ou usuário incorreto!");

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btnEntrar.png"))); // NOI18N
        btnEntrar.setBorder(null);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCadastrar.setText("Não tem uma conta? Cadastre-se");
        lblCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseExited(evt);
            }
        });

        lblEntrarComoAdm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEntrarComoAdm.setText("Entrar como Administrador");
        lblEntrarComoAdm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblEntrarComoAdmFocusGained(evt);
            }
        });
        lblEntrarComoAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrarComoAdmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntrarComoAdmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEntrarComoAdmMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addComponent(lblCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSenhaIncorreta, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEntrarComoAdm)
                            .addComponent(btnEntrar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(213, 213, 213))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(panelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadastrar)
                    .addComponent(lblSenhaIncorreta))
                .addGap(90, 90, 90)
                .addComponent(btnEntrar)
                .addGap(72, 72, 72)
                .addComponent(lblEntrarComoAdm)
                .addGap(28, 28, 28))
        );

        getContentPane().add(panelLogin);

        setSize(new java.awt.Dimension(606, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPassword.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        adicionarFocusGainedEstiloBorda(panelEmail);
        if (txtEmail.getText().equals("Email")) {
            txtEmail.requestFocus();
            txtEmail.setText(null);
            removerPlaceHolderEstilo(txtEmail);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        adicionarFocusLostEstiloBorda(panelEmail);
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Email");
            adicionarPlaceHolderEstilo(txtEmail);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnEyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEyeActionPerformed
        if (btnEye.isSelected()) {
            btnEye.setIcon(new ImageIcon(getClass().getResource("/assets/btnEyeIsVisible.png")));
            txtPassword.setEchoChar((char) 0);

        } else {
            btnEye.setIcon(new ImageIcon(getClass().getResource("/assets/btnEyeNotVisible.png")));
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_btnEyeActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnEntrar.doClick();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        adicionarFocusLostEstiloBorda(panelPassword);
        if (txtPassword.getText().equals("")) {
            txtPassword.setText("Senha");
            txtPassword.setEchoChar((char) 0);
            adicionarPlaceHolderEstilo(txtPassword);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        adicionarFocusGainedEstiloBorda(panelPassword);
        if (txtPassword.getText().equals("Senha")) {
            txtPassword.requestFocus();
            txtPassword.setText(null);
            txtPassword.setEchoChar('*');
            removerPlaceHolderEstilo(txtPassword);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        lblSenhaIncorreta.setVisible(false);
        String email, senha, emailVerif, nivelInvestimento;
        email = txtEmail.getText();
        senha = txtPassword.getText();

        if (email.equals("Email") || senha.equals("Senha")) {
            adicionarEstiloBordaDeErro();
        } else {
            Usuario usuario = new Usuario(email, senha);
            BancoDeDados bd;
            try {
                bd = new BancoDeDados();
                ResultSet rs = bd.ler(usuario);
                if (rs.next()) {
                    emailVerif = rs.getString("email");
                    nivelInvestimento = rs.getString("nivel_investimento");
                    if (emailVerif.equals("adm@gmail.com")) {
                        new PaginaAdministrador().setVisible(true);
                        dispose();
                    }else{
                        new PaginaUsuario(usuario).setVisible(true);
                        dispose();
                    }
                }else{
                    adicionarEstiloBordaDeErro();
                    
                }

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseEntered
        lblCadastrar.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblCadastrarMouseEntered

    private void lblCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseExited
        lblCadastrar.setForeground(Color.black);
    }//GEN-LAST:event_lblCadastrarMouseExited

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        new PaginaCadastro().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCadastrarMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        lblSenhaIncorreta.setVisible(false);
    }//GEN-LAST:event_txtEmailMouseClicked

    private void lblEntrarComoAdmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblEntrarComoAdmFocusGained

    }//GEN-LAST:event_lblEntrarComoAdmFocusGained

    private void lblEntrarComoAdmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarComoAdmMouseEntered
        lblEntrarComoAdm.setForeground(Color.blue);
    }//GEN-LAST:event_lblEntrarComoAdmMouseEntered

    private void lblEntrarComoAdmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarComoAdmMouseExited
        lblEntrarComoAdm.setForeground(Color.black);
    }//GEN-LAST:event_lblEntrarComoAdmMouseExited

    private void lblEntrarComoAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarComoAdmMouseClicked
        lblSenhaIncorreta.setVisible(false);
        removerEstiloBordaDeErro();
        txtEmail.setText("adm@gmail.com");
        txtPassword.setText("Senha");
        txtPassword.requestFocus();
    }//GEN-LAST:event_lblEntrarComoAdmMouseClicked

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(new FlatMacLightLaf());
                    break;

                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaAdministrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JToggleButton btnEye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblEntrarComoAdm;
    private javax.swing.JLabel lblSenhaIncorreta;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
